#!/usr/bin/env python
import os
import sys

ROOT_PATH = os.path.dirname(os.getcwd())
os.environ["GOFRI_ROOT_PATH"] = ROOT_PATH

from gofri.lib.project_generator.cli import execute_command

def generate(from_file=False):
    execute_command(ROOT_PATH, sys.argv, from_file)

if __name__ == '__main__':
    generate()
