#!/usr/bin/env python
import os
import sys
from gofri.lib.project_generator.cli import execute_command

def generate(from_file=False):
    ROOT_PATH = os.path.dirname(os.getcwd())
    execute_command(ROOT_PATH, sys.argv, from_file)

if __name__ == '__main__':
    generate()
